# Generated by Django 4.2.30 on 2026-07-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_seed_categories_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_priority',
            field=models.IntegerField(default=0, help_text='الأعلى يظهر أولاً بين المنتجات المميّزة', verbose_name='أولوية الظهور'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='منتج مميّز'),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
    ]
