# Generated by Django 4.2.30 on 2026-07-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_featured_priority_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_priority',
            field=models.IntegerField(blank=True, default=0, help_text='الأعلى يظهر أولاً بين المنتجات المميّزة', verbose_name='أولوية الظهور'),
        ),
    ]
