# Generated by Django 4.2.30 on 2026-07-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_seed_more_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='الصق قيمة "content" من وسم التحقق google-site-verification فقط.', max_length=200, verbose_name='رمز التحقق من Google Search Console'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, help_text='وصف مختصر (حتى 160 حرفاً) يظهر في نتائج بحث جوجل للصفحة الرئيسية.', max_length=300, verbose_name='وصف الموقع لمحركات البحث (Meta Description)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='كلمات يفصل بينها فاصلة، مثل: أردوينو, حسّاسات, روبوت, قطع إلكترونية.', max_length=300, verbose_name='كلمات مفتاحية'),
        ),
    ]
