# Generated by Django 4.2.30 on 2026-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_thumbnail_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='هاتف المقيّم'),
        ),
    ]
