# Generated by Django 4.2.30 on 2026-07-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_review_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalvideo',
            name='code',
            field=models.TextField(blank=True, verbose_name='الكود (Arduino)'),
        ),
        migrations.AddField(
            model_name='educationalvideo',
            name='components',
            field=models.TextField(blank=True, help_text='اكتب مكوّناً في كل سطر.', verbose_name='المكوّنات المطلوبة'),
        ),
        migrations.AddField(
            model_name='educationalvideo',
            name='source',
            field=models.CharField(blank=True, help_text='اسم صاحب الفيديو/المصدر (للأمانة).', max_length=300, verbose_name='المصدر'),
        ),
    ]
