# Generated by Django 4.2.30 on 2026-07-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_seed_arduino_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalvideo',
            name='wiring',
            field=models.TextField(blank=True, help_text='كل توصيلة في سطر، مثل: طرف الحسّاس Trig ← الطرف 9.', verbose_name='طريقة التوصيل'),
        ),
    ]
