# Generated by Django 4.2.30 on 2026-07-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_more_full_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalvideo',
            options={'ordering': ('project_number', 'id')},
        ),
        migrations.AddField(
            model_name='educationalvideo',
            name='project_number',
            field=models.IntegerField(default=0, help_text='رقم متسلسل لتسهيل البحث عن المشروع.', verbose_name='رقم المشروع'),
        ),
    ]
