# Generated by Django 4.2.30 on 2026-07-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_group4_and_renumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='الجهاز/الاسم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اشتراك إشعارات',
                'verbose_name_plural': 'اشتراكات الإشعارات',
            },
        ),
    ]
