# Generated by Django 4.2.30 on 2026-08-10 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True, verbose_name='معرّف الجهاز')),
                ('name', models.CharField(help_text='مثل: حاسبة أنور', max_length=100, verbose_name='الاسم')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='رمز الاتصال')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جهاز نقطة بيع',
                'verbose_name_plural': 'أجهزة نقاط البيع',
            },
        ),
        migrations.CreateModel(
            name='PosEvent',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('entity', models.CharField(db_index=True, max_length=30)),
                ('entity_uuid', models.CharField(db_index=True, max_length=64)),
                ('op', models.CharField(max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.CharField(max_length=40)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حدث مزامنة',
                'verbose_name_plural': 'أحداث المزامنة',
                'ordering': ('seq',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='product',
            name='pos_updated_at',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('product_uuid', models.CharField(db_index=True, max_length=64)),
                ('delta', models.IntegerField(verbose_name='التغيير')),
                ('reason', models.CharField(choices=[('opening', 'رصيد افتتاحي'), ('sale', 'بيع في المحل'), ('sale_void', 'إلغاء وصل'), ('return', 'إرجاع من زبون'), ('adjust', 'تسوية يدوية'), ('online_order', 'طلب من الموقع'), ('online_order_cancel', 'إلغاء طلب من الموقع')], default='adjust', max_length=30)),
                ('ref_type', models.CharField(blank=True, max_length=20)),
                ('ref_uuid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.CharField(max_length=40)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='store.product')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ('-received_at',),
            },
        ),
    ]
