# Generated by Django 4.2.30 on 2026-08-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_posdevice_posevent_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='مثل 1.3.2 — أرقام يفصلها نقاط', max_length=20, unique=True, verbose_name='رقم الإصدار')),
                ('installer', models.FileField(upload_to='releases/', verbose_name='ملف التنصيب (MSI)')),
                ('notes', models.TextField(blank=True, help_text='يظهر للمستخدم في نافذة التحديث. سطر لكل تغيير.', verbose_name='ما الجديد')),
                ('is_active', models.BooleanField(default=True, help_text='أزل العلامة لإيقاف توزيع هذا الإصدار فوراً.', verbose_name='منشور')),
                ('is_mandatory', models.BooleanField(default=False, help_text='يُطلب التحديث بإلحاح ولا يُسمح بتأجيله.', verbose_name='تحديث إلزامي')),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64, verbose_name='بصمة الملف')),
                ('size_bytes', models.BigIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إصدار البرنامج',
                'verbose_name_plural': 'إصدارات البرنامج',
                'ordering': ('-created_at',),
            },
        ),
    ]
