# Generated by Django 4.2.30 on 2026-08-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_apprelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='posevent',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='المستخدم'),
        ),
    ]
