# Generated by Django 4.2.30 on 2026-08-12 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_posevent_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
