# Generated by Django 4.2.30 on 2026-08-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_productimage_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='series',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
