# Generated by Django 4.2.30 on 2026-09-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_product_series_delete_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_filled',
            field=models.BooleanField(default=False, help_text='مُلئ اسمه/سعره تلقائياً ويحتاج مراجعتك. صفِّ القائمة بهذا الحقل لمراجعة الدفعة.', verbose_name='مملوء تلقائياً'),
        ),
        migrations.AddField(
            model_name='product',
            name='competitor_price',
            field=models.FloatField(blank=True, help_text='معدّل سعر المنافسين (أوروك/أردنك). تقارن به لوحة الأسعار بالألوان. فارغ = لا مقارنة.', null=True, verbose_name='سعر المنافس'),
        ),
        migrations.AddField(
            model_name='product',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='لم يُحدَّد اسمه/سعره بثقة — راجعه أولاً.', verbose_name='يحتاج انتباهاً'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='ملاحظة المراجعة'),
        ),
    ]
