# Generated by Django 4.2.30 on 2026-09-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_product_auto_filled_product_competitor_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='legacy_name',
            field=models.CharField(blank=True, editable=False, help_text='الاسم كما أُدخل يدوياً في نقطة البيع قبل التسمية التلقائية — للأرشفة والمقارنة.', max_length=300, verbose_name='الاسم الأصلي (قبل التعديل)'),
        ),
    ]
