# Generated by Django 4.2.30 on 2026-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_product_legacy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
            ],
            options={
                'verbose_name': 'مراجعة وتسعير منتج',
                'verbose_name_plural': '⭐ مراجعة وتسعير المنتجات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='aliexpress_url',
            field=models.URLField(blank=True, help_text='رابط المنتج على علي إكسبريس (مصدر سعر الشراء).', max_length=600, verbose_name='رابط علي إكسبريس'),
        ),
        migrations.AddField(
            model_name='product',
            name='competitor_url',
            field=models.URLField(blank=True, help_text='رابط المنتج عند أردنك أو أي متجر عراقي (مصدر سعر المقارنة).', max_length=600, verbose_name='رابط المنافس'),
        ),
    ]
