# Generated by Django 4.2.30 on 2026-09-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_productreview_product_aliexpress_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='أشّره عند مراجعتك للعنصر واعتماده. تأشيره يزيل علامة «يحتاج انتباهاً».', verbose_name='تم الفحص'),
        ),
    ]
