# Generated by Django 4.2.30 on 2026-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_product_alibaba_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.FloatField(blank=True, help_text='تكلفة المنتج بالدولار من علي إكسبريس/علي بابا. منه يُحسب سعر الشراء والبيع تلقائياً وفق سعر الصرف والهوامش في إعدادات الموقع.', null=True, verbose_name='السعر الدولاري (المصدر)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='profit_margin_pct',
            field=models.FloatField(default=35, help_text='نسبة الربح فوق سعر الشراء لتحديد سعر البيع. مثال: 35 تعني +\u200f%35.', verbose_name='هامش الربح %'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_margin_pct',
            field=models.FloatField(default=30, help_text='نسبة تُضاف فوق التكلفة الدولارية لتغطية الشحن. مثال: 30 تعني +\u200f%30.', verbose_name='هامش الشحن %'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usd_rate',
            field=models.FloatField(default=1600, help_text='كم ديناراً يساوي الدولار الواحد. منه يُحوَّل السعر الدولاري إلى سعر الشراء.', verbose_name='سعر صرف الدولار (دينار لكل دولار)'),
        ),
    ]
