# Generated by Django 4.2.30 on 2026-10-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_product_price_usd_sitesettings_profit_margin_pct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'دورة تدريبية', 'verbose_name_plural': '🎓 الدورات التدريبية'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'زبون', 'verbose_name_plural': '👥 الزبائن'},
        ),
        migrations.AlterModelOptions(
            name='downloadablefile',
            options={'verbose_name': 'ملف للتحميل', 'verbose_name_plural': 'الملفات للتحميل'},
        ),
        migrations.AlterModelOptions(
            name='educationalvideo',
            options={'ordering': ('project_number', 'id'), 'verbose_name': 'فيديو تعليمي', 'verbose_name_plural': '🎬 الفيديوهات التعليمية'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'طلب', 'verbose_name_plural': '🧾 الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'عنصر طلب', 'verbose_name_plural': 'عناصر الطلب'},
        ),
        migrations.AlterModelOptions(
            name='phoneotp',
            options={'verbose_name': 'رمز تحقق هاتف', 'verbose_name_plural': 'رموز تحقق الهاتف'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': '📦 المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='salereservation',
            options={'ordering': ('-created_at',), 'verbose_name': 'حجز بيع (أونلاين)', 'verbose_name_plural': 'حجوزات البيع (أونلاين)'},
        ),
        migrations.AlterModelOptions(
            name='sitesection',
            options={'ordering': ['order', 'id'], 'verbose_name': 'قسم في الصفحة الرئيسية', 'verbose_name_plural': 'أقسام الصفحة الرئيسية'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'id'], 'verbose_name': 'عضو فريق', 'verbose_name_plural': '👔 فريق العمل'},
        ),
    ]
